# Starts (or re-applies) the platform. Regenerates compose.mounts.yaml from the database (extra folders you added in the
# admin console + shell network switch), re-validating every folder here too, then runs docker compose up.
# Usage: powershell -ExecutionPolicy Bypass -File C:\llm-platform\scripts\platform-up.ps1 [-Build] [-Search]
param([switch]$Build, [switch]$Search)
$ErrorActionPreference = 'Stop'
$plat = Join-Path (Split-Path $PSScriptRoot -Parent) 'platform'
# docker writes progress to stderr; PowerShell 5.1 would turn that into terminating errors under 'Stop'.
function Invoke-Docker { $ErrorActionPreference = 'Continue'; & docker @args 2>&1 | ForEach-Object { "$_" }; $global:DockerExit = $LASTEXITCODE }
if (-not (Test-Path "$plat\secrets\pg_app.txt")) { & "$PSScriptRoot\platform-setup.ps1" }
Push-Location $plat
try {
    $override = "$plat\compose.mounts.yaml"
    if (-not (Test-Path $override)) { [IO.File]::WriteAllText($override, "# generated by platform-up.ps1`nservices: {}`n") }
    Invoke-Docker compose up -d --wait postgres | Out-Null
    if ($DockerExit) { throw 'postgres did not become healthy (docker compose logs postgres)' }
    $env:PGPASSWORD = (Get-Content "$plat\secrets\pg_superuser.txt" -Raw).Trim()
    $q = "SELECT coalesce(json_agg(json_build_object('name',name,'host',host_path,'cp',container_path,'access',access)),'[]') FROM app.workspace_roots WHERE kind='extra' AND enabled; SELECT coalesce((SELECT value::text FROM app.permission_settings WHERE key='shell_network'),'false');"
    $rows = @(Invoke-Docker compose exec -T -e PGPASSWORD postgres psql -U postgres -d aiplatform -At -c $q)
    Remove-Item Env:\PGPASSWORD
    $extra = @(); $shellNet = $false
    if ($DockerExit -eq 0 -and $rows.Count -ge 2 -and $rows[0] -like '[[]*') { $extra = @(($rows[0] | ConvertFrom-Json)); $shellNet = ($rows[1] -eq 'true') }
    $forbidden = '^[a-z]:\\?$|^[a-z]:\\(windows|program files|program files \(x86\)|programdata|\$recycle\.bin|system volume information)(\\|$)|^[a-z]:\\users\\?$|^[a-z]:\\users\\[^\\]+\\?$|^[a-z]:\\users\\[^\\]+\\(appdata|\.ssh|\.aws|\.azure|\.docker|\.kube|\.gnupg)(\\|$)|^\\\\'
    $lines = New-Object System.Collections.ArrayList; $mounts = New-Object System.Collections.ArrayList
    $mountsRo = New-Object System.Collections.ArrayList
    foreach ($r in $extra) {
        $hp = [string]$r.host; $low = $hp.ToLower()
        if ($low -match $forbidden -or $low.StartsWith($plat.ToLower()) -or $r.cp -notmatch '^/extra/[a-z0-9][a-z0-9_-]{0,39}$' -or $r.access -notin @('ro', 'rw')) { Write-Warning "Refusing to mount $hp (protected location)"; continue }
        if (-not (Test-Path -LiteralPath $hp -PathType Container)) { Write-Warning "Skipping $hp (folder not found)"; continue }
        [void]$mounts.Add(('      - "{0}:{1}:{2}"' -f ($hp -replace '\\', '/'), $r.cp, $r.access)); [void]$mountsRo.Add(('      - "{0}:{1}:ro"' -f ($hp -replace '\\', '/'), $r.cp))
    }
    [void]$lines.Add('# generated by platform-up.ps1 from the admin console settings - do not edit'); [void]$lines.Add('services:')
    foreach ($svc in @('backend', 'tool-runner', 'tool-runner-broad')) {
        $block = New-Object System.Collections.ArrayList; $list = if ($svc -eq 'tool-runner') { $mountsRo } else { $mounts }
        if ($list.Count) { [void]$block.Add('    volumes:'); $list | ForEach-Object { [void]$block.Add($_) } }
        if ($svc -eq 'tool-runner-broad' -and $shellNet) { [void]$block.Add('    network_mode: !reset null'); [void]$block.Add('    networks: [runner_net]') }
        if ($block.Count) { [void]$lines.Add("  ${svc}:"); $block | ForEach-Object { [void]$lines.Add($_) } }
    }
    if ($lines.Count -eq 2) { $lines[1] = 'services: {}' }
    [IO.File]::WriteAllText($override, ($lines -join "`n") + "`n")
    $profiles = if ($Search) { @('--profile', 'search') } else { @() }
    $upArgs = @('compose') + $profiles + @('-f', 'compose.yaml', '-f', 'compose.mounts.yaml', 'up', '-d', '--wait', '--remove-orphans') + $(if ($Build) { @('--build') } else { @() })
    Invoke-Docker @upArgs | Out-Host
    if ($DockerExit) { throw 'docker compose up failed (docker compose logs backend)' }
    Remove-Item "$plat\config\runtime\restart-required.json" -ErrorAction SilentlyContinue
    Write-Host "Mounted extra folders: $($mounts.Count)  |  shell network: $shellNet"
    Write-Host 'Ready:  chat http://127.0.0.1:8090   admin http://127.0.0.1:8090/admin   API docs http://127.0.0.1:8090/docs'
} finally { Pop-Location }
