# One-time (idempotent) setup for the local AI platform: secrets, workspace folders, .env. Never overwrites existing secrets.
# Usage: powershell -ExecutionPolicy Bypass -File C:\llm-platform\scripts\platform-setup.ps1 [-Workspace C:\AIWorkspace] [-ModelsDir C:\llm\models]
param([string]$Workspace = 'C:\AIWorkspace', [string]$ModelsDir = 'C:\llm\models')
$ErrorActionPreference = 'Stop'
$plat = Join-Path (Split-Path $PSScriptRoot -Parent) 'platform'
$sec = Join-Path $plat 'secrets'

function New-Secret([int]$Bytes) { $b = New-Object byte[] $Bytes; [Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($b); -join ($b | ForEach-Object { $_.ToString('x2') }) }
function Set-OwnerOnlyAcl([string]$Path) { $isDir = Test-Path $Path -PathType Container; $a = if ($isDir) { New-Object Security.AccessControl.DirectorySecurity } else { New-Object Security.AccessControl.FileSecurity }; $a.SetAccessRuleProtection($true, $false); $inh = if ($isDir) { 'ContainerInherit,ObjectInherit' } else { 'None' }; foreach ($id in @([Security.Principal.WindowsIdentity]::GetCurrent().User, (New-Object Security.Principal.SecurityIdentifier 'S-1-5-18'))) { $a.AddAccessRule((New-Object Security.AccessControl.FileSystemAccessRule($id, 'FullControl', $inh, 'None', 'Allow'))) }; (Get-Item -LiteralPath $Path -Force).SetAccessControl($a) }

New-Item -ItemType Directory -Force $sec, (Join-Path $plat 'backups'), (Join-Path $plat 'config\runtime') | Out-Null
Set-OwnerOnlyAcl $sec
$made = @()
foreach ($s in @(@{ N = 'pg_superuser'; B = 32 }, @{ N = 'pg_owner'; B = 32 }, @{ N = 'pg_app'; B = 32 }, @{ N = 'pg_backup'; B = 32 }, @{ N = 'session_key'; B = 48 }, @{ N = 'admin_bootstrap'; B = 15 })) {
    $f = Join-Path $sec "$($s.N).txt"
    if (Test-Path $f) { continue }
    [IO.File]::WriteAllText($f, (New-Secret $s.B)); Set-OwnerOnlyAcl $f; $made += $s.N
}
if (-not (Test-Path (Join-Path $sec 'README.md'))) { [IO.File]::WriteAllText((Join-Path $sec 'README.md'), "Generated by scripts\platform-setup.ps1. Never commit or share these files. Rotate: see docs\DEVELOPMENT.md.`n") }
if (-not (Test-Path (Join-Path $plat 'backups\.gitkeep'))) { [IO.File]::WriteAllText((Join-Path $plat 'backups\.gitkeep'), '') }

foreach ($d in @('allowed', 'projects', 'sandbox')) { New-Item -ItemType Directory -Force (Join-Path $Workspace $d) | Out-Null }
$readme = Join-Path $Workspace 'README.txt'
if (-not (Test-Path $readme)) { [IO.File]::WriteAllText($readme, "AI workspace. allowed = read-only for the AI, projects = read/write (deletes ask), sandbox = scratch area.`r`nThe AI cannot see anything outside this folder unless you add a folder in the admin console.`r`n") }

$envText = "AIP_WORKSPACE_DIR=$($Workspace -replace '\\', '/')`nAIP_MODELS_DIR=$($ModelsDir -replace '\\', '/')`nAIP_PLATFORM_DIR=$($plat -replace '\\', '/')`n"
[IO.File]::WriteAllText((Join-Path $plat '.env'), $envText)
$emb = Join-Path $ModelsDir 'Qwen3-Embedding-0.6B-Q8_0.gguf'
if (-not (Test-Path $emb)) { Write-Warning "Embedding model missing: $emb (download Qwen/Qwen3-Embedding-0.6B-GGUF, file Qwen3-Embedding-0.6B-Q8_0.gguf)" }

Write-Host "Secrets: $sec $(if ($made) { '(created: ' + ($made -join ', ') + ')' } else { '(all present, unchanged)' })"
Write-Host "Workspace: $Workspace (allowed, projects, sandbox)"
if ($made -contains 'admin_bootstrap') { Write-Host "Admin console login: user 'admin', password in $sec\admin_bootstrap.txt (you must change it at first login)" }
